session_type_labels = [{1 'LT, laser on/off at reward'};...
                       {2 'LT, laser on/off laps'};...
                       {3 '5 sec laser pulses'};...
                       {4 '60 sec laser pulses'};...
                       {5 'ripple triggered stim'};...
                       {6 'delayed ripple-stim'};...
                       {7 'sleep closely following ripple-triggered stim'};...
                       {8 'sleep, no stim'};
                       {10 'novel'};...
                       {11 'run'};...
                       {12 'sleep'};...
                       {13 'Brad task no laser'};...
                       {14 'Brad task laser'};...
                       {16 'asleep in Brad maze'};...
                       {100 'other'}];

